baseurl = "https://dmturner.co.uk/"
title = "David Turner - Full-stack web developer"
author = "David Turner"
canonifyurls = true
languagecode = "en-gb"

enableEmoji = true


[permalinks]
  blog = "/:title/"


pygmentsstyle       = "monokai"
pygmentscodefences  = true

[params]
  siteshorturl = "dmturner.co.uk"
  sitename = "David Turner"
  sitedesc = "Full-stack web developer based in Lancashire, UK"
  disableWebFonts = false


[[menu.main]]
    name = "About me"
    url  = "/about-me"
#[[menu.main]]
#    name = "Portfolio"
#    url  = "#"
#[[menu.main]]
#    name = "Contact"
#    url  = "#"
