baseurl = "https://dmturner.co.uk"
title = "David Turner - Full-stack web developer"
author = "David Turner"
canonifyurls = true
languagecode = "en-gb"
#theme = "black-and-light"

pygmentsstyle       = "monokai"
pygmentscodefences  = true

[params]
  siteshorturl = "dmturner.co.uk"
  sitename = "David Turner"
  sitedesc = "Full-stack web developer"
  disableWebFonts = false


[[menu.main]]
    name = "About me"
    url  = "/about"
#[[menu.main]]
#    name = "Portfolio"
#    url  = "#"
#[[menu.main]]
#    name = "Contact"
#    url  = "#"