baseurl = "https://dmturner.co.uk/"
title = "David Turner - Full-stack web developer"
author = "David Turner"
canonifyurls = true
languagecode = "en-gb"


[taxonomies]
# Disable the default taxonomies
# tag = "" <-- don't disable this one
category = ""



enableEmoji = true


# [permalinks]
#   blog = "/:title/"


pygmentsstyle       = "monokai"
pygmentscodefences  = true

[params]
  siteshorturl = "dmturner.co.uk"
  sitename = "David Turner"
  sitedesc = "Full-stack web developer based in Lancashire, UK"
  disableWebFonts = false
  builtWithText = "Built with :heart: using "


[[menu.main]]
    name = "Blog"
    url  = "/blog"
[[menu.main]]
    name = "About"
    url  = "/about"
#[[menu.main]]
#    name = "Contact"
#    url  = "#"
