baseurl = "https://dmturner.co.uk"
title = "D.M. Turner"
author = "David Turner"
canonifyurls = true
languagecode = "en-gb"
theme = "black-and-light"

pygmentsstyle       = "monokai"
pygmentscodefences  = true

[params]
  sitename = "David Turner"
  sitedesc = "Full stack web developer"
  disableWebFonts = false


#[[menu.main]]
#    name = "About me"
#    url  = "/about"
#[[menu.main]]
#    name = "Portfolio"
#    url  = "#"
#[[menu.main]]
#    name = "Contact"
#    url  = "#"