baseurl = "https://dmturner.netlify.app"
title = "D.M. Turner"
author = "David Turner"
canonifyurls = true
languagecode = "en-gb"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "D.M. Turner"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Portfolio"
    url  = "/portfolio"
[[menu.main]]
    name = "Contact"
    url  = "/contact"