baseurl = "https://dmturner.co.uk"
title = "D.M. Turner"
author = "David Turner"
canonifyurls = true
languagecode = "en-gb"
theme = "black-and-light"


[params]
  sitename = "David Turner"
  sitedesc = "something here"
  disableWebFonts = false


[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Portfolio"
    url  = "#"
[[menu.main]]
    name = "Contact"
    url  = "#"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4