[build]
  publish = "public"
  command = "hugo && mv public/_headers.txt public/_headers"

[build.environment]
  HUGO_VERSION = "0.147.8" # Change this to the version you need
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENABLEGITINFO = "true"